resolver: lts-19.8

packages:
- '.'
- '../libraries/Cabal/Cabal'
- '../libraries/Cabal/Cabal-syntax'

nix:
   enable: false
   packages:
   - autoconf
   - automake
   - gcc
   - git
   - ncurses
   - perl
