#define RTS_AARCH64_SYMBOLS \
    SymE_HasProto(__aarch64_cas16_acq) \
    SymE_HasProto(__aarch64_cas16_acq_rel) \
    SymE_HasProto(__aarch64_cas16_rel) \
    SymE_HasProto(__aarch64_cas16_relax) \
    SymE_HasProto(__aarch64_cas16_sync) \
    SymE_HasProto(__aarch64_cas1_acq) \
    SymE_HasProto(__aarch64_cas1_acq_rel) \
    SymE_HasProto(__aarch64_cas1_rel) \
    SymE_HasProto(__aarch64_cas1_relax) \
    SymE_HasProto(__aarch64_cas1_sync) \
    SymE_HasProto(__aarch64_cas2_acq) \
    SymE_HasProto(__aarch64_cas2_acq_rel) \
    SymE_HasProto(__aarch64_cas2_rel) \
    SymE_HasProto(__aarch64_cas2_relax) \
    SymE_HasProto(__aarch64_cas2_sync) \
    SymE_HasProto(__aarch64_cas4_acq) \
    SymE_HasProto(__aarch64_cas4_acq_rel) \
    SymE_HasProto(__aarch64_cas4_rel) \
    SymE_HasProto(__aarch64_cas4_relax) \
    SymE_HasProto(__aarch64_cas4_sync) \
    SymE_HasProto(__aarch64_cas8_acq) \
    SymE_HasProto(__aarch64_cas8_acq_rel) \
    SymE_HasProto(__aarch64_cas8_rel) \
    SymE_HasProto(__aarch64_cas8_relax) \
    SymE_HasProto(__aarch64_cas8_sync) \
    SymE_HasProto(__aarch64_ldadd1_acq) \
    SymE_HasProto(__aarch64_ldadd1_acq_rel) \
    SymE_HasProto(__aarch64_ldadd1_rel) \
    SymE_HasProto(__aarch64_ldadd1_relax) \
    SymE_HasProto(__aarch64_ldadd1_sync) \
    SymE_HasProto(__aarch64_ldadd2_acq) \
    SymE_HasProto(__aarch64_ldadd2_acq_rel) \
    SymE_HasProto(__aarch64_ldadd2_rel) \
    SymE_HasProto(__aarch64_ldadd2_relax) \
    SymE_HasProto(__aarch64_ldadd2_sync) \
    SymE_HasProto(__aarch64_ldadd4_acq) \
    SymE_HasProto(__aarch64_ldadd4_acq_rel) \
    SymE_HasProto(__aarch64_ldadd4_rel) \
    SymE_HasProto(__aarch64_ldadd4_relax) \
    SymE_HasProto(__aarch64_ldadd4_sync) \
    SymE_HasProto(__aarch64_ldadd8_acq) \
    SymE_HasProto(__aarch64_ldadd8_acq_rel) \
    SymE_HasProto(__aarch64_ldadd8_rel) \
    SymE_HasProto(__aarch64_ldadd8_relax) \
    SymE_HasProto(__aarch64_ldadd8_sync) \
    SymE_HasProto(__aarch64_ldclr1_acq) \
    SymE_HasProto(__aarch64_ldclr1_acq_rel) \
    SymE_HasProto(__aarch64_ldclr1_rel) \
    SymE_HasProto(__aarch64_ldclr1_relax) \
    SymE_HasProto(__aarch64_ldclr1_sync) \
    SymE_HasProto(__aarch64_ldclr2_acq) \
    SymE_HasProto(__aarch64_ldclr2_acq_rel) \
    SymE_HasProto(__aarch64_ldclr2_rel) \
    SymE_HasProto(__aarch64_ldclr2_relax) \
    SymE_HasProto(__aarch64_ldclr2_sync) \
    SymE_HasProto(__aarch64_ldclr4_acq) \
    SymE_HasProto(__aarch64_ldclr4_acq_rel) \
    SymE_HasProto(__aarch64_ldclr4_rel) \
    SymE_HasProto(__aarch64_ldclr4_relax) \
    SymE_HasProto(__aarch64_ldclr4_sync) \
    SymE_HasProto(__aarch64_ldclr8_acq) \
    SymE_HasProto(__aarch64_ldclr8_acq_rel) \
    SymE_HasProto(__aarch64_ldclr8_rel) \
    SymE_HasProto(__aarch64_ldclr8_relax) \
    SymE_HasProto(__aarch64_ldclr8_sync) \
    SymE_HasProto(__aarch64_ldeor1_acq) \
    SymE_HasProto(__aarch64_ldeor1_acq_rel) \
    SymE_HasProto(__aarch64_ldeor1_rel) \
    SymE_HasProto(__aarch64_ldeor1_relax) \
    SymE_HasProto(__aarch64_ldeor1_sync) \
    SymE_HasProto(__aarch64_ldeor2_acq) \
    SymE_HasProto(__aarch64_ldeor2_acq_rel) \
    SymE_HasProto(__aarch64_ldeor2_rel) \
    SymE_HasProto(__aarch64_ldeor2_relax) \
    SymE_HasProto(__aarch64_ldeor2_sync) \
    SymE_HasProto(__aarch64_ldeor4_acq) \
    SymE_HasProto(__aarch64_ldeor4_acq_rel) \
    SymE_HasProto(__aarch64_ldeor4_rel) \
    SymE_HasProto(__aarch64_ldeor4_relax) \
    SymE_HasProto(__aarch64_ldeor4_sync) \
    SymE_HasProto(__aarch64_ldeor8_acq) \
    SymE_HasProto(__aarch64_ldeor8_acq_rel) \
    SymE_HasProto(__aarch64_ldeor8_rel) \
    SymE_HasProto(__aarch64_ldeor8_relax) \
    SymE_HasProto(__aarch64_ldeor8_sync) \
    SymE_HasProto(__aarch64_ldset1_acq) \
    SymE_HasProto(__aarch64_ldset1_acq_rel) \
    SymE_HasProto(__aarch64_ldset1_rel) \
    SymE_HasProto(__aarch64_ldset1_relax) \
    SymE_HasProto(__aarch64_ldset1_sync) \
    SymE_HasProto(__aarch64_ldset2_acq) \
    SymE_HasProto(__aarch64_ldset2_acq_rel) \
    SymE_HasProto(__aarch64_ldset2_rel) \
    SymE_HasProto(__aarch64_ldset2_relax) \
    SymE_HasProto(__aarch64_ldset2_sync) \
    SymE_HasProto(__aarch64_ldset4_acq) \
    SymE_HasProto(__aarch64_ldset4_acq_rel) \
    SymE_HasProto(__aarch64_ldset4_rel) \
    SymE_HasProto(__aarch64_ldset4_relax) \
    SymE_HasProto(__aarch64_ldset4_sync) \
    SymE_HasProto(__aarch64_ldset8_acq) \
    SymE_HasProto(__aarch64_ldset8_acq_rel) \
    SymE_HasProto(__aarch64_ldset8_rel) \
    SymE_HasProto(__aarch64_ldset8_relax) \
    SymE_HasProto(__aarch64_ldset8_sync) \
    SymE_HasProto(__aarch64_swp1_acq) \
    SymE_HasProto(__aarch64_swp1_acq_rel) \
    SymE_HasProto(__aarch64_swp1_rel) \
    SymE_HasProto(__aarch64_swp1_relax) \
    SymE_HasProto(__aarch64_swp1_sync) \
    SymE_HasProto(__aarch64_swp2_acq) \
    SymE_HasProto(__aarch64_swp2_acq_rel) \
    SymE_HasProto(__aarch64_swp2_rel) \
    SymE_HasProto(__aarch64_swp2_relax) \
    SymE_HasProto(__aarch64_swp2_sync) \
    SymE_HasProto(__aarch64_swp4_acq) \
    SymE_HasProto(__aarch64_swp4_acq_rel) \
    SymE_HasProto(__aarch64_swp4_rel) \
    SymE_HasProto(__aarch64_swp4_relax) \
    SymE_HasProto(__aarch64_swp4_sync) \
    SymE_HasProto(__aarch64_swp8_acq) \
    SymE_HasProto(__aarch64_swp8_acq_rel) \
    SymE_HasProto(__aarch64_swp8_rel) \
    SymE_HasProto(__aarch64_swp8_relax) \
    SymE_HasProto(__aarch64_swp8_sync)
